/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author User
 */
public class jdlAlmacenUnitarios extends javax.swing.JDialog {

    /**
     * Creates new form jdlAlmacenUnitarios
     */
    public jdlAlmacenUnitarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducsUnit = new tableNew.Table();
        jLabel51 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarUnitProduct = new javax.swing.JTextField();
        roundPanel1 = new controller.RoundPanel();
        txtCodProductoUni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioUnit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtStockUnit = new javax.swing.JTextField();
        lblImagenUnit = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();
        btnCambiarFoto = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProducsUnit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Descripción", "Categoria", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProducsUnit);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 720, 370));

        jLabel51.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(153, 153, 153));
        jLabel51.setText("PRODUCTOS DE UNIDADES");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 330, 60));

        jLabel2.setText("Buscar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        txtBuscarUnitProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarUnitProductActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscarUnitProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 500, 40));

        roundPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        roundPanel1.add(txtCodProductoUni, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 70, 40));

        jLabel5.setText("Codigo:");
        roundPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setText("Precio:");
        roundPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        txtPrecioUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioUnitActionPerformed(evt);
            }
        });
        roundPanel1.add(txtPrecioUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 110, 40));

        jLabel1.setText("Stock:");
        roundPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        txtStockUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockUnitActionPerformed(evt);
            }
        });
        roundPanel1.add(txtStockUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 110, 40));

        lblImagenUnit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        roundPanel1.add(lblImagenUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 140, 150));

        btnEliminarProducto.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrar.png"))); // NOI18N
        btnEliminarProducto.setText("Eliminar Producto");
        btnEliminarProducto.setBorder(null);
        btnEliminarProducto.setFocusPainted(false);
        btnEliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarProductoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarProductoMousePressed(evt);
            }
        });
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        roundPanel1.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 160, 40));

        btnGuardarCambios.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardarCambios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/guardar.png"))); // NOI18N
        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.setBorder(null);
        btnGuardarCambios.setFocusPainted(false);
        btnGuardarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarCambiosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarCambiosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarCambiosMousePressed(evt);
            }
        });
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });
        roundPanel1.add(btnGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 160, 40));

        btnCambiarFoto.setText("Cambiar");
        btnCambiarFoto.setFocusable(false);
        roundPanel1.add(btnCambiarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        jPanel1.add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 720, 200));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 740, 30, 30));

        jLabel6.setText("Numero de productos:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 746, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioUnitActionPerformed

    private void txtBuscarUnitProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarUnitProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarUnitProductActionPerformed

    private void txtStockUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockUnitActionPerformed

    private void btnEliminarProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProductoMouseEntered
        btnEliminarProducto.setBackground(new Color(0, 0, 0));
        btnEliminarProducto.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnEliminarProductoMouseEntered

    private void btnEliminarProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProductoMouseExited
        btnEliminarProducto.setBackground(new Color(204, 204, 204));
        btnEliminarProducto.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnEliminarProductoMouseExited

    private void btnEliminarProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProductoMousePressed

    }//GEN-LAST:event_btnEliminarProductoMousePressed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed

    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnGuardarCambiosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCambiosMouseEntered
       btnGuardarCambios.setBackground(new Color(0, 0, 0));
        btnGuardarCambios.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnGuardarCambiosMouseEntered

    private void btnGuardarCambiosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCambiosMouseExited
  btnGuardarCambios.setBackground(new Color(204, 204, 204));
        btnGuardarCambios.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnGuardarCambiosMouseExited

    private void btnGuardarCambiosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCambiosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCambiosMousePressed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlAlmacenUnitarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlAlmacenUnitarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlAlmacenUnitarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlAlmacenUnitarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlAlmacenUnitarios dialog = new jdlAlmacenUnitarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambiarFoto;
    public javax.swing.JButton btnEliminarProducto;
    public javax.swing.JButton btnGuardarCambios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblImagenUnit;
    public javax.swing.JLabel lblTotal;
    private controller.RoundPanel roundPanel1;
    public tableNew.Table tblProducsUnit;
    public javax.swing.JTextField txtBuscarUnitProduct;
    public javax.swing.JTextField txtCodProductoUni;
    public javax.swing.JTextField txtPrecioUnit;
    public javax.swing.JTextField txtStockUnit;
    // End of variables declaration//GEN-END:variables
}
