/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.controladorPagos;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import model.Cliente;

import model.ClienteDAO;

public class jdlRealizarPago extends javax.swing.JDialog {

    final Cliente cliente;
    double pagadoActual;
  
    
    double restanteNow;

    public double getRestanteNow() {
        return restanteNow;
    }

    public void settRestanteNow(double restantenow) {
        this.restanteNow = restantenow;
    }

      public double getPagadoActual() {
        return pagadoActual;
    }

    public void setgetPagadoActual(double pagadoActual) {
        this.pagadoActual = pagadoActual;
    }

    public jdlRealizarPago(newprincipal parent, boolean modal, Cliente cl) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        cliente = cl;
        controladorPagos cp = new controladorPagos(parent, this);
  txtPagarNew.addKeyListener(new KeyAdapter() {
    @Override
    public void keyTyped(KeyEvent e) {
        char c = e.getKeyChar();
        // Permite dígitos y el punto decimal
        if (!Character.isDigit(c) && c != '.') {
            e.consume();  // Consume el evento para evitar que se ingrese el carácter no numérico o el punto decimal adicional
        }
        // Permite solo un punto decimal
        if (c == '.' && txtPagarNew.getText().contains(".")) {
            e.consume();  // Consume el evento si ya hay un punto decimal en el texto
        }
    }
});

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPagarNew = new javax.swing.JTextField();
        txtCodPagar = new javax.swing.JTextField();
        txtMembrePago = new javax.swing.JTextField();
        txtFaltaPagar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSaldoNew = new javax.swing.JTextField();
        btnActualizarPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 620, 70));

        jLabel52.setFont(new java.awt.Font("Corbel", 0, 36)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(153, 153, 153));
        jLabel52.setText("REALIZAR PAGO");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 320, 40));

        jLabel1.setText("Pago:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 40, -1));

        jLabel2.setText("Codigo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel3.setText("Membresia S/:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 110, -1));

        jLabel4.setText("Falta pagar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 70, -1));
        jPanel1.add(txtPagarNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, 40));
        jPanel1.add(txtCodPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 140, 40));
        jPanel1.add(txtMembrePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 140, 40));
        jPanel1.add(txtFaltaPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 140, 40));

        jLabel5.setText("Saldo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 70, 40));
        jPanel1.add(txtSaldoNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 140, 40));

        btnActualizarPago.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizarPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar (2).png"))); // NOI18N
        btnActualizarPago.setText("ACTUALIZAR");
        btnActualizarPago.setBorder(null);
        btnActualizarPago.setFocusPainted(false);
        btnActualizarPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarPagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarPagoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnActualizarPagoMousePressed(evt);
            }
        });
        btnActualizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPagoActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void btnActualizarPagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPagoMouseEntered
        btnActualizarPago.setBackground(new Color(0, 0, 0));
        btnActualizarPago.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnActualizarPagoMouseEntered

    private void btnActualizarPagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPagoMouseExited
        btnActualizarPago.setBackground(new Color(204, 204, 204));
        btnActualizarPago.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnActualizarPagoMouseExited

    private void btnActualizarPagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPagoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarPagoMousePressed


    private void btnActualizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPagoActionPerformed


    }//GEN-LAST:event_btnActualizarPagoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlRealizarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlRealizarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlRealizarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlRealizarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente cl = new Cliente(); // Declara e inicializa una instancia de Cliente
                newprincipal principal = new newprincipal();
                ClienteDAO clientedao = new ClienteDAO(); // Inicializa una instancia de newprincipal
                jdlRealizarPago dialog = new jdlRealizarPago(principal, true, cl);

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtCodPagar;
    public javax.swing.JTextField txtFaltaPagar;
    public javax.swing.JTextField txtMembrePago;
    public javax.swing.JTextField txtPagarNew;
    public javax.swing.JTextField txtSaldoNew;
    // End of variables declaration//GEN-END:variables
}
