/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import conexionBD.conexion;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Productos;
import model.ProductosDao;

/**
 *
 * @author User
 */
public class jdlRegistrarProductoUnitario extends javax.swing.JDialog {

    Productos pr;
    ProductosDao productosDao;

    public jdlRegistrarProductoUnitario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        productosDao = new ProductosDao();
        productosDao.obtenerProximoCodigo(txtCodProduct);

        pr = new Productos();
        productosDao.llenarComboBoxCategorias(cbxCategorias, pr);

        txtPrecioProduct.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();  // Consume el evento para evitar que se ingrese el carácter no numérico

                }
            }
        });
        txtStockProduc.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();  // Consume el evento para evitar que se ingrese el carácter no numérico

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        txtDescripcionProduct = new javax.swing.JTextField();
        txtPrecioProduct = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombreProduct = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodProduct = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrarProd = new javax.swing.JButton();
        cbxCategorias = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtStockProduc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 850, 40));

        jLabel62.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(153, 153, 153));
        jLabel62.setText("UNIDAD");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 140, 40));

        lblImage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO DEL PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 170, 170));

        txtDescripcionProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionProductActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescripcionProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 440, 40));
        jPanel1.add(txtPrecioProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 60, 40));

        jLabel1.setText("Descripción:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 166, -1, 50));
        jPanel1.add(txtNombreProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 190, 40));

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 96, -1, 30));

        jLabel4.setText("Codigo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 40));

        txtCodProduct.setEnabled(false);
        jPanel1.add(txtCodProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 70, 40));

        jLabel6.setText("Precio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 60, -1));

        btnRegistrarProd.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistrarProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/agregar-archivo.png"))); // NOI18N
        btnRegistrarProd.setText("REGISTRAR");
        btnRegistrarProd.setBorder(null);
        btnRegistrarProd.setFocusPainted(false);
        btnRegistrarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarProdMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistrarProdMousePressed(evt);
            }
        });
        btnRegistrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 170, 40));

        cbxCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 160, 50));

        jLabel7.setText("Stock:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 60, -1));

        jLabel8.setText("Categoría:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 60, -1));
        jPanel1.add(txtStockProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/foto.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarProdMouseEntered
        btnRegistrarProd.setBackground(new Color(0, 0, 0));
        btnRegistrarProd.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnRegistrarProdMouseEntered

    private void btnRegistrarProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarProdMouseExited
        btnRegistrarProd.setBackground(new Color(204, 204, 204));
        btnRegistrarProd.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnRegistrarProdMouseExited

    private void btnRegistrarProdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarProdMousePressed

    }//GEN-LAST:event_btnRegistrarProdMousePressed

    private void btnRegistrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProdActionPerformed

    }//GEN-LAST:event_btnRegistrarProdActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtDescripcionProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlRegistrarProductoUnitario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlRegistrarProductoUnitario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlRegistrarProductoUnitario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlRegistrarProductoUnitario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlRegistrarProductoUnitario dialog = new jdlRegistrarProductoUnitario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrarProd;
    public javax.swing.JComboBox<String> cbxCategorias;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblImage;
    public javax.swing.JTextField txtCodProduct;
    public javax.swing.JTextField txtDescripcionProduct;
    public javax.swing.JTextField txtNombreProduct;
    public javax.swing.JTextField txtPrecioProduct;
    public javax.swing.JTextField txtStockProduc;
    // End of variables declaration//GEN-END:variables
}
