/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ControladorAlmacenPorcion;
import controller.ControladorAlmacenUnitario;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class JdlTipoAlmacen extends javax.swing.JDialog {

    /**
     * Creates new form JdlTipoAlmacen
     */
    public JdlTipoAlmacen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        btnUnidad = new javax.swing.JButton();
        btnScoops = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 400, 40));

        jLabel62.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(153, 153, 153));
        jLabel62.setText("ALMACEN");
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 170, 40));

        btnUnidad.setBackground(new java.awt.Color(255, 255, 255));
        btnUnidad.setText("POR UNIDAD");
        btnUnidad.setFocusPainted(false);
        btnUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUnidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUnidadMouseExited(evt);
            }
        });
        btnUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnidadActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 40));

        btnScoops.setBackground(new java.awt.Color(255, 255, 255));
        btnScoops.setText("POR SCOOPS");
        btnScoops.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnScoopsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnScoopsMouseExited(evt);
            }
        });
        btnScoops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoopsActionPerformed(evt);
            }
        });
        getContentPane().add(btnScoops, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidadMouseEntered
        btnUnidad.setBackground(new Color(0, 0, 0));
        btnUnidad.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnUnidadMouseEntered

    private void btnUnidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidadMouseExited
        btnUnidad.setBackground(new Color(255, 255, 255));
        btnUnidad.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnUnidadMouseExited

    private void btnUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnidadActionPerformed
        Frame parentFrame = (Frame) SwingUtilities.getWindowAncestor(this);

        // Crea una instancia de jdlRegistrarProducto con el Frame como padre
        jdlAlmacenUnitarios regisProduct = new jdlAlmacenUnitarios(parentFrame, true);
        newprincipal np=new newprincipal();

        ControladorAlmacenUnitario cr=new ControladorAlmacenUnitario(np, regisProduct);
regisProduct.txtCodProductoUni.setEnabled(false);
regisProduct.tblProducsUnit.fixTable(regisProduct.jScrollPane1);
        // Muestra el segundo JDialog
        regisProduct.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnUnidadActionPerformed

    private void btnScoopsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnScoopsMouseEntered
        btnScoops.setBackground(new Color(0, 0, 0));
        btnScoops.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnScoopsMouseEntered

    private void btnScoopsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnScoopsMouseExited
        btnScoops.setBackground(new Color(255, 255, 255));
        btnScoops.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnScoopsMouseExited

    private void btnScoopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoopsActionPerformed
        Frame parentFrame = (Frame) SwingUtilities.getWindowAncestor(this);

        // Crea una instancia de jdlRegistrarProducto con el Frame como padre
        jdlAlmacenPorcion almacenPor = new jdlAlmacenPorcion(parentFrame, true);
        newprincipal np=new newprincipal();
        ControladorAlmacenPorcion ru=new ControladorAlmacenPorcion(np, almacenPor);
                almacenPor.txtCodProductoPor.setEnabled(false);

        almacenPor.tblProducsPor.fixTable(almacenPor.jScrollPane1);

        // Muestra el segundo JDialog
        almacenPor.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnScoopsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdlTipoAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdlTipoAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdlTipoAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdlTipoAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdlTipoAlmacen dialog = new JdlTipoAlmacen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnScoops;
    public javax.swing.JButton btnUnidad;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
