/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatIntelliJLaf;
import controller.Slide;
import java.awt.Color;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class splashcreen extends javax.swing.JFrame {

    Slide sl;
    private Timer timer;

    public splashcreen() {
        initComponents();
        sl = new Slide();
        setLocationRelativeTo(null);

        sl.LabelAbajo(-90, 20, 30, 10, imgMancuerna);
        sl.LabelAbajo(30, 160, 30, 10, lbltext);
      iniciarAnimacionCarga();
      Shape forma = new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), 50, 50);
        setShape(forma);
    }

    private void iniciarAnimacionCarga() {
        int delay = 10; // Intervalo de tiempo en milisegundos entre cada cambio de valor de la barra
        int incremento = 1; // Incremento en el valor de la barra en cada iteración
        int valorMaximo = 100; // Valor máximo de la barra de progreso

        timer = new Timer(delay, new ActionListener() {
            int progreso = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (progreso <= valorMaximo) {
                    BARRA.setValue(progreso);
                    progreso += incremento;
                } else {
                    // La animación ha terminado, puedes ocultar la barra de progreso o realizar otras acciones
                    timer.stop();
                    dispose(); // Cierra la ventana de splashcreen
           
                    LoginApp pr=new LoginApp();
                   pr.setVisible(true);
                }
            }
        });

        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        imgMancuerna = new javax.swing.JLabel();
        BARRA = new javax.swing.JProgressBar();
        lbltext = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 47));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgMancuerna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/gimnasio.png"))); // NOI18N
        jPanel2.add(imgMancuerna, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -90, 150, 130));

        BARRA.setBackground(new java.awt.Color(0, 0, 47));
        BARRA.setForeground(new java.awt.Color(255, 255, 255));
        BARRA.setBorderPainted(false);
        BARRA.setPreferredSize(new java.awt.Dimension(14, 14));
        jPanel2.add(BARRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 660, 40));

        lbltext.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbltext.setForeground(new java.awt.Color(255, 255, 255));
        lbltext.setText("LUCIANO´S GYM");
        jPanel2.add(lbltext, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/giphy-2--unscreen.gif"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 60, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cargando...");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                  
                try {
                    UIManager.setLookAndFeel(new FlatIntelliJLaf());

                // Personaliza el estilo del encabezado de la tabla
                UIManager.put("TableHeader.background", new Color(21, 21, 21));
                UIManager.put("TableHeader.foreground", Color.WHITE);
                } catch (UnsupportedLookAndFeelException ex) {

                }

            
                
                new splashcreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BARRA;
    private javax.swing.JLabel imgMancuerna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbltext;
    // End of variables declaration//GEN-END:variables
}
